language: ruby
rvm:
  - "2.1.1"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - cd spec/dummy
  - bundle exec rake db:create db:migrate
  - cd ../..
script: xvfb-run bundle exec rspec
